POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYyYjE4MWU0YWQyOTAyOTUyMjRlYTI4OCIsImlhdCI6MTY1NTgwNTk5OX0.d8j0xjCwngLng12wtRtWBjYHXWumI-3U0eQshpVMIjw

{
    "content": "Root user tried to create this note",
    "important": false
}